<a href="https://colab.research.google.com/github/aaalexlit/big-data-hadoop-spark-edx-course/blob/main/course_2_custom_distributed_training/Week1_Tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import tensorflow as tf
import numpy as np
import random
x = tf.constant([4, 2])
print(x)

tf.Tensor([4 2], shape=(2,), dtype=int32)


In [38]:
a = np.array([1, 2, 3])
b = tf.constant(a)
a[0] = 4
print(b) 

tf.Tensor([4 2 3], shape=(3,), dtype=int64)


In [39]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1, ))
])

In [40]:
model.variables

[<tf.Variable 'dense_1/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.5182897]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [41]:
vector = tf.Variable(initial_value= [1, 2])
print(vector)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [42]:
vector = tf.Variable([1, 2], dtype=tf.float32)
print(vector)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>


In [43]:
tf.Variable([[1, 2], [3, 4]])

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [44]:
mammal = tf.Variable("Elephant", dtype=tf.string)
print(mammal)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Elephant'>


In [45]:
its_complicated = tf.Variable(4 + 3j, dtype=tf.complex64)
print(its_complicated)

<tf.Variable 'Variable:0' shape=() dtype=complex64, numpy=(4+3j)>


In [46]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [47]:
tf.constant([1,2,3,4,5,6], shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [48]:
tf.constant(-1.0, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>

In [49]:
tf.constant(-1.0, shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>

In [50]:
tf.add([1, 2], [3, 4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [51]:
tf.square(5)

<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [52]:
tf.reduce_sum([1, 2, 3])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [53]:
tf.square(2) + tf.square(3)

<tf.Tensor: shape=(), dtype=int32, numpy=13>

## Eager execution

In [54]:
x = 2
x_squared = tf.square(x)
print(f"{x_squared}")

4


## Broadcasting

In [55]:
a = tf.constant([[1, 2],
                 [3, 4]])
tf.add(a, 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

## Operator overloading

In [56]:
a = tf.constant([[1, 2],
                 [3, 4]])
a ** 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

## NumPy Compatibility

In [57]:
a = tf.constant(5)
b = tf.constant(3)

np.multiply(a, b)

15

## NumPy Interoperability

In [58]:
ndarray = np.ones([3, 3])
ndarray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
tensor = tf.multiply(ndarray, 3)
print(tensor)
tensor.numpy()

tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]], shape=(3, 3), dtype=float64)


array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

## Evaluating variables

In [60]:
v = tf.Variable(0.0)
v + 1

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [61]:
v = tf.Variable(0.0)
v.assign_add(1)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=1.0>

In [62]:
v.read_value().numpy()

1.0

## Evaluating variables withing custom models

In [63]:
class MyLayer(tf.keras.layers.Layer):
  def __init__(self):
    super(MyLayer, self).__init__()
    self.my_var = tf.Variable(100)
    self.my_other_var_list = [tf.Variable(x) for x in range(2)]

m = MyLayer()
[var.numpy() for var in m.variables]

[100, 0, 1]

In [64]:
[var for var in m.variables]

[<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>]